"""Desktop shell and layout. All actions use MainWindow's existing run gates."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QWidget, QFrame, QLabel, QPushButton, QLineEdit,
    QVBoxLayout, QHBoxLayout, QStackedWidget, QPlainTextEdit, QScrollArea)

from .catalog import ExerciseCatalog
from .widgets import VideoCanvas, MetricCard, Disclosure, NoticeLabel


def build_workspace(w):
    central = QWidget()
    w.setCentralWidget(central)
    root = QHBoxLayout(central)
    root.setContentsMargins(0, 0, 0, 0)
    root.setSpacing(0)
    sidebar = QFrame()
    sidebar.setObjectName('sidebar')
    sidebar.setFixedWidth(208)
    nav = QVBoxLayout(sidebar)
    nav.setContentsMargins(16, 26, 16, 22)
    nav.setSpacing(7)
    brandrow = QHBoxLayout()
    mark = QLabel('康')
    mark.setObjectName('brandMark')
    mark.setAlignment(Qt.AlignmentFlag.AlignCenter)
    mark.setFixedSize(44, 44)
    brandrow.addWidget(mark)
    brand = QLabel('康复助手')
    brand.setObjectName('brand')
    brandrow.addWidget(brand)
    nav.addLayout(brandrow)
    nav.addSpacing(34)
    label = QLabel('康复管理')
    label.setObjectName('navHeading')
    nav.addWidget(label)
    nav.addSpacing(5)

    def nav_button(label, callback, layout=nav):
        button = QPushButton(label)
        button.setObjectName('nav')
        button.setCheckable(True)
        button.setCursor(Qt.CursorShape.PointingHandCursor)
        button.clicked.connect(callback)
        layout.addWidget(button)
        return button

    w.scene_buttons = {'rehab': nav_button('身体评估', w._show_catalog)}
    w.training_nav = nav_button('训练指导', lambda: w._select_rehab('training'))
    w.body_nav = nav_button('身体档案', w._show_body)
    w.history_nav = nav_button('历史记录', w._history)
    nav.addSpacing(22)
    tools = Disclosure('其他工具')
    for scene, label in (('activity', '日常活动'), ('bedroom_demo', '卧室观察演示'), ('safety_demo', '安全提示演示')):
        w.scene_buttons[scene] = nav_button(label, lambda checked=False, s=scene: w._select_scene(s), tools.box)
    w.tools_disclosure = tools
    nav.addWidget(tools)
    nav.addStretch()
    events = QPushButton('事件记录')
    events.setObjectName('textButton')
    events.clicked.connect(w._events)
    nav.addWidget(events, alignment=Qt.AlignmentFlag.AlignLeft)
    w.coverage = QLabel('当前未开始观察')
    w.coverage.setObjectName('muted')
    w.coverage.setWordWrap(True)
    nav.addWidget(w.coverage)
    nav.addSpacing(12)
    version = QLabel('本地版  ·  0.4')
    version.setObjectName('muted')
    nav.addWidget(version)
    root.addWidget(sidebar)

    body = QVBoxLayout()
    body.setContentsMargins(26, 24, 26, 18)
    body.setSpacing(16)
    heading = QHBoxLayout()
    titlebox = QVBoxLayout()
    titlebox.setSpacing(6)
    w.title = QLabel('身体评估')
    w.title.setObjectName('pageTitle')
    titlebox.addWidget(w.title)
    w.subtitle = QLabel()
    w.subtitle.setObjectName('muted')
    titlebox.addWidget(w.subtitle)
    heading.addLayout(titlebox, 1)
    w.status_badge = QLabel('相机未打开')
    w.status_badge.setObjectName('badge')
    heading.addWidget(w.status_badge, alignment=Qt.AlignmentFlag.AlignVCenter)
    body.addLayout(heading)

    person = QFrame()
    person.setObjectName('personBar')
    person_row = QHBoxLayout(person)
    person_row.setContentsMargins(14, 8, 14, 8)
    person_row.addWidget(QLabel('当前用户'))
    w.participant = QLineEdit(w.participant_id)
    w.participant.setPlaceholderText('用户编号')
    w.participant.setAccessibleName('当前用户编号')
    w.participant.setMaxLength(80)
    w.participant.setMaximumWidth(220)
    w.participant.returnPressed.connect(w._apply_participant)
    w.participant.textChanged.connect(lambda: w._buttons())
    person_row.addWidget(w.participant)
    w.participant_button = QPushButton('切换 / 新建用户')
    w.participant_button.setObjectName('textButton')
    w.participant_button.clicked.connect(w._apply_participant)
    person_row.addWidget(w.participant_button)
    person_row.addStretch()
    w.person_hint = QLabel('记录按用户分别保存')
    w.person_hint.setObjectName('muted')
    person_row.addWidget(w.person_hint)
    body.addWidget(person)
    w.notice = NoticeLabel()
    w.notice.setObjectName('notice')
    w.notice.setWordWrap(True)
    w.notice.setVisible(False)
    body.addWidget(w.notice)

    w.pages = QStackedWidget()
    w.work_page = QWidget()
    work = QVBoxLayout(w.work_page)
    work.setContentsMargins(0, 0, 0, 0)
    work.setSpacing(12)
    w._source_card(work)
    split = QHBoxLayout()
    split.setSpacing(16)
    monitor = QVBoxLayout()
    monitor.setSpacing(12)
    task = QFrame()
    task.setObjectName('taskHeader')
    taskbox = QHBoxLayout(task)
    taskbox.setContentsMargins(16, 10, 16, 10)
    title_stack = QVBoxLayout()
    title_stack.setSpacing(3)
    w.task_title = QLabel()
    w.task_title.setObjectName('sectionTitle')
    title_stack.addWidget(w.task_title)
    w.task_meta = QLabel()
    w.task_meta.setObjectName('muted')
    title_stack.addWidget(w.task_meta)
    taskbox.addLayout(title_stack, 1)
    w.catalog_button = QPushButton('更换动作')
    w.catalog_button.setObjectName('textButton')
    w.catalog_button.clicked.connect(w._show_catalog)
    taskbox.addWidget(w.catalog_button)
    monitor.addWidget(task)

    w.canvas = VideoCanvas()
    w.canvas.roi_changed.connect(w._roi_changed)
    monitor.addWidget(w.canvas, 1)
    meta = QHBoxLayout()
    w.source_badge = QLabel('摄像头 · 未打开')
    w.source_badge.setObjectName('muted')
    meta.addWidget(w.source_badge, 1)
    w.frame_info = QLabel()
    w.frame_info.setObjectName('muted')
    meta.addWidget(w.frame_info)
    monitor.addLayout(meta)
    metrics = QHBoxLayout()
    metrics.setSpacing(10)
    w.count_card = MetricCard('完成次数', ' 次')
    w.angle_card = MetricCard('当前角度', '°')
    w.valid_card = MetricCard('有效观察', '%')
    for item in (w.count_card, w.angle_card, w.valid_card):
        metrics.addWidget(item, 1)
    monitor.addLayout(metrics)
    w.feedback = QLabel('打开相机，检查拍摄位置。')
    w.feedback.setObjectName('feedback')
    w.feedback.setWordWrap(True)
    monitor.addWidget(w.feedback)
    # The debug checkbox remains an accessible disclosure; it is not in the
    # daily workflow. Full diagnostic evidence remains available when needed.
    w.debug_details = Disclosure('识别详情')
    w.debug_toggle = w.debug_details.toggle
    w.debug = QPlainTextEdit()
    w.debug.setReadOnly(True)
    w.debug.setMaximumHeight(125)
    w.debug_details.box.addWidget(w.debug)
    monitor.addWidget(w.debug_details)
    monitor_host = QWidget()
    monitor_host.setObjectName('scrollContent')
    monitor_host.setLayout(monitor)
    monitor.setContentsMargins(0, 0, 6, 0)
    w.monitor_scroll = QScrollArea()
    w.monitor_scroll.setWidgetResizable(True)
    w.monitor_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
    w.monitor_scroll.setWidget(monitor_host)
    split.addWidget(w.monitor_scroll, 1)
    w.setup_panel = w._setup_panel()
    w.setup_panel.setFixedWidth(328)
    split.addWidget(w.setup_panel)
    work.addLayout(split, 1)

    actions = QHBoxLayout()
    actions.setSpacing(10)
    w.preview_button = QPushButton('打开预览')
    w.preview_button.clicked.connect(w._preview)
    w.confirm_button = QPushButton('确认准备')
    w.confirm_button.clicked.connect(w._confirm)
    w.start_button = QPushButton('开始评估')
    w.start_button.setObjectName('primary')
    w.start_button.clicked.connect(lambda: w._send('start'))
    w.stop_button = QPushButton('完成并保存')
    w.stop_button.clicked.connect(w._finish_task)
    w.privacy_button = QPushButton('停止采集')
    w.privacy_button.setToolTip('停止并释放相机；重新开始需要再次预览和确认。')
    w.privacy_button.setObjectName('danger')
    w.privacy_button.clicked.connect(lambda: w._send('privacy', reason='privacy_pause'))
    w.retry_button = QPushButton('重试保存')
    w.retry_button.clicked.connect(lambda: w._send('retry_save'))
    w.backup_button = QPushButton('备份未保存结果')
    w.backup_button.clicked.connect(w._backup_pending)
    w.discard_button = QPushButton('丢弃本次结果')
    w.discard_button.clicked.connect(w._discard_pending)
    for button in (w.preview_button, w.confirm_button, w.start_button, w.stop_button,
                   w.privacy_button, w.retry_button, w.backup_button, w.discard_button):
        actions.addWidget(button)
    work.addLayout(actions)
    w.pages.addWidget(w.work_page)
    w._history_page()
    w._body_page()
    w.catalog = ExerciseCatalog()
    w.catalog.exercise_selected.connect(w._choose_catalog_exercise)
    w.pages.addWidget(w.catalog)
    body.addWidget(w.pages, 1)
    root.addLayout(body, 1)
    w._buttons()
